### ISSUE TITLE
Isnt this illegal?

### ISSUE THREAD

**Issue by LegacyGamerHD** [Speentie8081/BukKill_RemoteTerminal-cPanel#1]
Literally Devon this is no joke what your pasting not that its threat if run latest spigot but still

**Comment by Speentie8081** [comment]
It modifies the bytecode of the server jar, and infects all plugîns on the server.
The code is not infectious to other servers.

I can list a few reasons why this is NOT illegal-
1. By installing the plugin on the server as an admin you are responsible
2. It only infects the host server, it does not spread outside of the host
3. All risk involved is on the server admins and not the creator of the plugins
4. Spigot is already illegal as it is, so what are you really asking here?

I can list a few cases where it WOULD be illegal-
1. If you knowingly misrepresent the virus as being a good plugin to the admins
2. If you solicit the staff in regards to the virus
3. If you use the remote execution part of the plugin to harm their systems

I highly doubt this works on the latest Spigot, the last known version this worked on was 1.12.
